---
  title: "Modelo de campo medio SEIR ampliado"
author: Grupo covid19UNGS
date: '`r format(Sys.time(), "%d %B, %Y")`'
output: 
  html_document:
  theme: readable
toc: yes
toc_depth: 2
toc_float: true
editor_options: 
  chunk_output_type: console
bibliography: Epidemics.bib
---
  
```{r setup, include=FALSE,echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)

needed_packages <- c(
    "tidyverse"
  , "lubridate"
  , "pomp")

lapply(needed_packages, function(x) { if(!require(x,character.only = TRUE)) install.packages(x)} )

require(lubridate)
require(tidyverse)
theme_set(theme_bw())

#
# Setup variables globales
#
fit.with       <- "D"
fitting        <- FALSE   ## Small change in pomp objects if fitting or simulating

source("R/covid_pomp.R")

```


## Setup del objeto pomp

```{r setup_pomp, echo=FALSE, tidy=TRUE, message=FALSE, warning=FALSE}

# Falta leer archivo para comparar

cor<-read_csv('https://docs.google.com/spreadsheets/d/16-bnsDdmmgtSxdWbVMboIHo5FRuz76DBxsz_BbsEVWA/export?format=csv&id=16-bnsDdmmgtSxdWbVMboIHo5FRuz76DBxsz_BbsEVWA&gid=0')

unique(cor$osm_admin_level_4)

distrito.data <- cor %>% filter( osm_admin_level_4 =="CABA") %>% mutate(fecha=dmy(fecha), dias =as.numeric( fecha - min(fecha))) %>% 
  rename(fallecidos=nue_fallecidos_diff,casos=nue_casosconf_diff) %>% select(fecha,dias,casos,fallecidos,transmision_tipo)

#
# leer valores de parametros
#
read_csv("Data/params.csv")

covid.fitting <- distrito.data %>%
  pomp(
    time       = "dias"
  , t0         = 1
  , rprocess   = euler(sir_step, delta.t = 1/6)
  , rmeasure   = { 
   if (fit.with == "D") { rmeas_deaths } else if (fit.with == "H") { rmeas_hosp }
  }
  , dmeasure   = {
   if (fit.with == "D") { dmeas_deaths } else if (fit.with == "H") { dmeas_hosp }
  }
  , rinit      = sir_init
  , partrans   = par_trans
  , accumvars  = accum_names
  , paramnames = param_names
  , statenames = state_names) 

####
## Step 3: Simulate from the beginning and project forward with this beta0
## Would prefer pmcmc (see for_pmcmc) for uncertainty in beta0. Next step...
####

SEIR.sim <- do.call(
  pomp::simulate
  , list(
    object         = covid.fitting
    , times        = intervention.forecast@times
    , params = c(fixed_params
    , c(
      beta0              = variable_params[i, "beta0est"]
    , soc_dist_level_sip = variable_params[i, "soc_dist_level_sip"]
    , E0                 = variable_params[i, ]$E0
    , Ca                 = variable_params[i, ]$Ca
    , alpha              = variable_params[i, ]$alpha
    , delta              = variable_params[i, ]$delta
    , mu                 = variable_params[i, ]$mu
   , rho_d              = variable_params[i, ]$rho_d
   , rho_r              = variable_params[i, ]$rho_r
      ))
    , nsim         = nsim
    , format       = "d"
    , include.data = F
    , seed         = 1001)) %>% {
      rbind(.,
         group_by(., day) %>%
           select(-.id) %>%
           summarise_all(median) %>%
                    mutate(.id = "median"))
    } 





```